### PR TITLE
More Swift 4 Updates

### PR DESCRIPTION
**Pull request by getaclue00**
Hey guys,

This is just a build up on PR https://github.com/quire-io/SwiftyChrono/pull/6 and dealing with issue #5 

However I am stuck. 
I tried to run the tests but gave up after 2 hours of them just spinning there.
Maybe I need a better computer or maybe I am doing something wrong 🤔

Anywho, this update went on to refactor some: 
- `characters` call from strings removal
- depreciating the `substring` method
- some error out of bounds fixes

I think I got a good chunk of work done.
I wanted to submit this as a PR in case anyone can point me in the right direction so I can finish this and run the test suite =)

Without running the tests, anecdotally..., code above seem to work but I definitely haven't tested widely

Alex

### CODE REVIEW

**Comment by getaclue00** [comment]
I also noticed that one of the requirements is `iOS 9.0+` ... I only tested this on `iOS 11`
So, comments on this would be nice too

**Comment by getaclue00** [comment]
aight, so I got the English tests to start running

I isolated some broken tests. The commented tests are broken for `TestEN.swift:` `testExample` func
```swift
    private let files = [
//        "test_en",
        "test_en_casual",
        "test_en_dash",
        "test_en_deadline",
//        "test_en_inter_std",
//        "test_en_little_endian",
//        "test_en_middle_endian",
        "test_en_month",
        "test_en_option_forward",
        "test_en_relative",
        "test_en_slash",
        "test_en_time_ago",
//        "test_en_time_exp",
        "test_en_weekday",
    ]
```

**Comment by getaclue00** [comment]
Decided to isolate some more to see if there is a pattern. Same thing as above, commented out test files cause the suite to break.
```swift
class TestES: ChronoJSXCTestCase {
    private let files = [
        "test_es_casual",
        "test_es_dash",
        "test_es_deadline",
//        "test_es_little_endian",
        "test_es_slash",
        "test_es_time_ago",
        "test_es_time_exp",
    ]
````

```swift
class TestFR: ChronoJSXCTestCase {
    private let files = [
        "test_fr_casual",
        "test_fr_dash",
        "test_fr_deadline",
//        "test_fr_little_endian",
        "test_fr_slash",
        "test_fr_time_ago",
//        "test_fr_time_exp",
        "test_fr_weekday",
    ]
```

```swift
class TestZHHant: ChronoJSXCTestCase {
    private let files = [
        "test_zh_hant_casual",
        "test_zh_hant_date",
        "test_zh_hant_deadline",
//        "test_zh_hant_time_exp",
        "test_zh_hant_weekday",
    ]
```
So, it seems like `little_endian` test func has something there and `time_exp` test func as well

**Comment by getaclue00** [comment]
@jerrywell mind checking it over please when you got a second? would love some guidance!

**Comment by jerrywell** [comment]
Thank you for the contribution. as we accept the latest 4.2 pull request, i will close this one.

**Pull request closed without merging**
